import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { AuthContextWrapper } from '../src/context/AuthContextWrapper'
import { PairContextWrapper } from '../src/context/PairContextWrapper'
import Head from 'next/head'
import { MODAL_ROOT_ID } from '../src/utils/constants/elementIds'
import styled from 'styled-components'
import { COLOR_FONT_PRIMARY } from '../styles/constants/colors'

const SuzuchiGinkouClient = ({ Component, pageProps }: AppProps) => {
  return (
    <Wrapper>
      <Head>
        <title>Suzuchi Ginkou</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;400;600&display=swap"
          rel="stylesheet"
        />
      </Head>

      <div id={MODAL_ROOT_ID} />
      <AuthContextWrapper>
        <PairContextWrapper>
          <Component {...pageProps} />
        </PairContextWrapper>
      </AuthContextWrapper>
    </Wrapper>
  )
}

const Wrapper = styled.div`
  min-height: 100vh;
  height: 100vh;
  font-family: 'Poppins', sans-serif;
  color: ${COLOR_FONT_PRIMARY};
`

export default SuzuchiGinkouClient
