import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import Dashboard from './Dashboard'

const Home: NextPage = () => {
  return (
    <Wrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="modal-root" />
      <Dashboard />
    </Wrapper>
  )
}

const Wrapper = styled.div`
  min-height: 100vh;
  height: 100vh;
`

export default Home
